# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
#    - python: 3.4
#      env: TOXENV=py34
#    - python: 3.5
#      env: TOXENV=py35
#    - python: 3.6
#      env: TOXENV=py36
brances:
    except:
        - stdevNorge_t17_pyskycoin_ci_appveyor_config
before_install:
    - curl -sL -o ~/bin/gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme
    - chmod +x ~/bin/gimme

install:
    - pip install tox-travis
    - eval "$(gimme 1.10)"
    - sudo apt-get update && sudo apt-get install swig

script: make test

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

