image: Visual Studio 2017

environment:
    global:
        #CYG_ROOT: C:\cygwin64
        #CYG_MIRROR: http://cygwin.mirror.constant.com
        #CYG_CACHE: C:\cygwin64\var\cache\setup
        #CYG_BASH: C:\cygwin64\bin\bash
        GOOS: windows
        GOARCH: amd64

    matrix:
        - PYTHON: "C:\\Python27"
#          #- PYTHON: "C:\\Python33"
#        - PYTHON: "C:\\Python34"
#        - PYTHON: "C:\\Python35"
#        - PYTHON: "C:\\Python27-x64"
#        - PYTHON: "C:\\Python33-x64"
#          DISTUTILS_USE_SDK: "1"
#        - PYTHON: "C:\\Python34-x64"
#          DISTUTILS_USE_SDK: "1"
#        - PYTHON: "C:\\Python35-x64"
#        - PYTHON: "C:\\Python36-x64"
#cache:
#    - '%CYG_CACHE%'

install:
    #    - '%CYG_ROOT%\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --packages autoconf,autogen,automake,cygwin-devel,git,gcc-core,gcc-g++,libncurses-devel,libprotobuf-devel,make,openssh,openssl-devel,pkg-config,zlib-devel,gcc,g++,gdb'
    #- '%CYG_ROOT%\bin\cygcheck -dc cygwin'
    - git submodule init
    - git submodule update
    - cd gopath/src/github.com/skycoin/skycoin
    - git checkout origin/stdevEclipse_t1568_swig_files
    - cd C:\projects\pyskycoin
    - "%PYTHON%\\python.exe -m pip install wheel tox"
      #- choco install make --source=cygwin
    - cinst swig
    - cinst mingw
#- ps: (new-object System.Net.WebClient).Downloadfile("https://downloads.sourceforge.net/project/tdm-gcc/TDM-GCC%20Installer/tdm64-gcc-5.1.0-2.exe?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Ftdm-gcc%2Ffiles%2FTDM-GCC%2520Installer%2Ftdm64-gcc-5.1.0-2.exe%2Fdownload&ts=1530907506", "$env:APPVEYOR_BUILD_FOLDER\\tdm-gcc.exe")
#    - ps: .\\tdm-gcc.exe

#build: off

test_script:
    - make test
    #- '%CYG_BASH% -lc "export OS=Windows_NT"'
    #- '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER && make test"'
